export const Skills: string[] = [
    "typescript",
    "javascript",
    "next.js",
    "react.js",
    "react native",
    "flutter",
    "node.js",
    "express.js",
    "redis",
    "upstash",
    "firebase",
    "supabase",
    "mongo db",
    "mysql",
    "motion",
    "tailwind css",
    "shadcn",
    "aceternity",
    "git",
    "github",
    "vercel",
    "render",
    "vscode",
    "antigravity",
    "cursor"
]